name: poc-llvm
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt  15.*
- clangdev 15.*
- clangxx 15.*
- cmake
- llvmdev 15.*
- lld 15.*
- meson
- ninja
- pkg-config
# run
- arrow-cpp 9.*
- arrow-c-glib 9.*
- cli11
- glog
- pip
# dev
- pre-commit
- pip:
  - makim==1.8.1
