name: pocllvm
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt
- clangdev 14.*
- clangxx 14.*
- cmake
- llvmdev 14.*
- lld 14.*
- meson
- ninja
- pkg-config
# run
- arrow-cpp 9.*
- arrow-c-glib 9.*
- cli11
- glog
# dev
- pre-commit
